### ISSUE TITLE
APIs for status and item data?

### ISSUE THREAD

**Issue by IamTechknow** [hzeller/stuff-org#10]
Hi there, I started frequenting Noisebridge, and after donating some old electronic components and finding out this repo, I wanted to see I can make a better mobile UI.

I noticed there is a search API but no API equivalent for the status page or viewing an item. I'm interested in making an Android app that integrates with parts.noisebridge.net (and generally other sites that use stuff-org if possible) as a project for my portfolio. I prefer to use endpoints as opposed to scraping the HTML, so would it be okay if I looked into creating API endpoints for these two things?

**Comment by hzeller** [comment]
Sure, go ahead.

I _think_ it might be easier to just make the HTML more mobile friendly, but having a full set of APIs are good to have and would certainly be make it more 'proper' to interface an app with it.

**Comment by IamTechknow** [comment]
Sounds good, thank you. I'll make a pull request eventually. I am new to Go, but I worked with Python and Django, so we'll see!

**Comment by IamTechknow** [comment]
Hey @hzeller, did you get a chance to review my PR?

**Comment by hzeller** [comment]
(sorry, I am travelling currently with only phone internet access; will have a look in two days)

**Comment by IamTechknow** [comment]
Since my PR is accepted, this may be closed now. In the near future I could look into enhancing the mobile web page
