### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by miloh** [hzeller/stuff-org#7]
in stuff/search-handler.go:
 build breaks with Error 2 on undefined: http:Pusher 

http:Pusher requires Go 1.8, which isn't even available in debian jessie backports

debian go versions ref:
https://packages.debian.org/search?keywords=golang

**Comment by hzeller** [comment]
The Debian packages are hopelessly outdated if not on Debian unstable. So in Jessie I usually use the binaries from https://golang.org/dl

**Comment by miloh** [comment]
excellent, all good!
